name: drerik
favicon: null
layout_spectrum: 0.73357
typography_spectrum: 0.14764185808598995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#abdcfd'
    - '#6d98e6'
    - '#466993'
    - '#232227'
  brandStrength: 0.625
  lightness: 0.16323660826310515
  saturation: 0.7609192738309503
  rhythmicContrast: 0.1545612160116434
purpose: []
